Feature/randomness
dbbs-lab/bsb-nest pull request #7
Opened 2024-05-13 17:17 UTC by drodarie

- Add randomness to NEST simulations (seed) 
- Allow NEST random distribution for neuron parameters

close #6

2024-05-14 09:01 UTC, Helveg requested changes

2024-05-14 09:01 UTC, Helveg commented on bsb_nest/distributions.py
> +from bsb import DistributionCastError, TypeHandler, config, types
Did you add `DistributionCastError`? Has this been released already?

2024-05-14 09:01 UTC, Helveg commented on bsb_nest/distributions.py
> +        if "_distr" not in self.__dict__:
```suggestion
        if not hasattr(self, "_distr"):
```

2024-05-14 09:01 UTC, Helveg commented on bsb_nest/distributions.py
> +        return "nest_parameter"
```suggestion
        return "nest parameter"
```

2024-05-14 09:01 UTC, Helveg commented on tests/test_nest.py
> +            _ = Configuration(conf)
```suggestion
            Configuration(conf)
```

2024-05-14 10:01 UTC, drodarie commented on bsb_nest/distributions.py
> +from bsb import DistributionCastError, TypeHandler, config, types
It was already there. It is also used for distribution attributes in bsb-core. I basically adapted the `Distribution` in bsb-core/bsb/config/_distributions.py

2024-05-14 10:31 UTC, drodarie commented
Hmm for some reason the `hasattr` you suggested does not work. 
To give some context, I copied the implementation of Distribution in _distributions.py in bsb.core, and here too the `__getattr__` uses `self.__dict__`. 
I will revert the change and put a comment but I am not sure why this happens

2024-05-15 11:14 UTC, Helveg commented
ah oops, I did not see that this was inside of `__getattr__`. It doesn't work because `hasattr` uses the entire Python attribute access cascade, including a lookup of `__getattr__` itself :)

2024-05-15 11:15 UTC, Helveg approved these changes
I'll approve it, but once `bsb-core` implements reproducibility/randomness systematically, this logic will probably have to be redone.

2024-05-20 14:47 UTC, merged